export const tareas = [
  {
    id: 1,
    descripcion: 'Lavar los platos',
    completado: false,
    prioridad: 'baja',
    fechaLimite: '2025-07-17',
  },
  {
    id: 2,
    descripcion: 'Estudiar Angular',
    completado: false,
    prioridad: 'alta',
    fechaLimite: '2025-07-18',
  },
  {
    id: 3,
    descripcion: 'Sacar la basura',
    completado: true,
    prioridad: 'media',
    fechaLimite: '2025-07-16',
  },
  {
    id: 4,
    descripcion: 'Hacer ejercicio',
    completado: false,
    prioridad: 'alta',
    fechaLimite: '2025-07-17',
  },
  {
    id: 5,
    descripcion: 'Leer un capítulo de un libro',
    completado: true,
    prioridad: 'media',
    fechaLimite: '2025-07-19',
  },
  {
    id: 6,
    descripcion: 'Regar las plantas',
    completado: false,
    prioridad: 'baja',
    fechaLimite: '2025-07-17',
  },
  {
    id: 7,
    descripcion: 'Preparar la cena',
    completado: false,
    prioridad: 'alta',
    fechaLimite: '2025-07-17',
  },
  {
    id: 8,
    descripcion: 'Enviar un correo importante',
    completado: true,
    prioridad: 'alta',
    fechaLimite: '2025-07-16',
  },
  {
    id: 9,
    descripcion: 'Organizar el escritorio',
    completado: false,
    prioridad: 'media',
    fechaLimite: '2025-07-20',
  },
  {
    id: 10,
    descripcion: 'Planear la semana',
    completado: false,
    prioridad: 'alta',
    fechaLimite: '2025-07-21',
  },
];
